; x86-64 Intel Syntax Assembly generated by CPlus Compiler
.intel_syntax	noprefix
.file			"examples/fibonacci.cp"
.section		.text
.globl			_start

.globl			fibonacci
fibonacci:
	push	rsp
	mov	rdp, rsp
	pop	rsp
	ret

.globl			main
main:
	push	rsp
	mov	rdp, rsp
	pop	rsp
	ret


_start:
	call	main
	mov	rdi, rax
	mov	rax, 60
	syscall
