# x86-64 Assembly generated by CPlus Compiler enfin supposed to be generated prc ça generate pas encore ça mdrr
	.intel_syntax noprefix
	.file "examples/fibonacci.cp"
	.section .text
	.globl fibonacci
fibonacci:
	push rbp
	mov rbp, rsp
	#sub rsp, 16
	sub rsp, 24
    mov dword ptr [rbp - 4], edi
    cmp dword ptr [rbp - 4], 1
	jle .Lthen0
	mov eax, [rbp - 4]
	sub eax, 1
	mov edi, eax
	call fibonacci
    mov dword ptr [rbp - 8], eax
	mov eax, [rbp - 4]
	sub eax, 2
	mov edi, eax
	call fibonacci
    add eax, dword ptr [rbp - 8]
	jmp .Lend1
.Lthen0:
	mov eax, [rbp - 4]
.Lend1:
	leave
	ret

	.globl main
main:
	push rbp
	mov rbp, rsp
    # sub rsp, 8
	mov edi, 10
	call fibonacci
	leave
	ret

.globl _start
_start:
    call main
    mov rdi, rax
    mov rax, 60
    syscall
