# x86-64 Intel Assembly generated by CPlus Compiler
	.intel_syntax	noprefix
	.file			"examples/return.cp"
	.section		.text

.globl			add
add:
	push	rbp
	mov		rbp, rsp
	mov		dword ptr [rbp-4], edi
	mov		dword ptr [rbp-8], esi
	mov		eax, dword ptr [rbp-4]
	add		eax, dword ptr [rbp-8]
	mov		dword ptr [rbp-12], eax
	mov		eax, dword ptr [rbp-12]
	leave
	ret

.globl			main
main:
	push	rbp
	mov		rbp, rsp
	sub		rsp, 16
	mov		edi, 1
	mov		esi, 2
	call	add
	mov		dword ptr [rbp-4], eax
	mov		eax, dword ptr [rbp-4]
	mov		dword ptr [rbp-8], eax
	mov		eax, dword ptr [rbp-8]
	leave
	ret


.globl			_start
_start:
	call	main
	mov		rdi, rax
	mov		rax, 60
	syscall
